version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fake_job_api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fake_job_ui
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
